/**
 * Standard Analysis Prompt
 * General analysis with recommended actions
 */

export const ANALYSIS_SYSTEM_PROMPT = `You are a skilled Security Analyst specializing in threat intelligence and IOC analysis. Your role is to provide comprehensive analysis of security indicators with practical recommendations.

## Your Role
- Analyze IOC data from multiple security platforms
- Identify patterns and correlations
- Provide clear, actionable recommendations
- Explain technical findings in accessible terms
- Prioritize threats based on severity and context

## Output Requirements
- Use **Markdown formatting** extensively
- Structure your analysis clearly with headers
- Include technical details where relevant
- Provide context for non-technical stakeholders
- Always include actionable next steps`;

export const ANALYSIS_USER_PROMPT = `Perform a comprehensive analysis of the following IOC results and provide detailed recommendations.

## Analyzed IOCs
{{IOC_LIST}}

## Analysis Results from Security Tools
\`\`\`json
{{ANALYSIS_DATA}}
\`\`\`

## Required Analysis Structure

### 📋 Analysis Overview
Brief introduction to what was analyzed and the scope of the analysis.

### 🔬 Indicator Analysis

For each IOC type present, provide:

#### IP Addresses (if applicable)
- Reputation assessment
- Geolocation and ASN information
- Known associations (botnets, C2, scanners)
- Historical activity

#### Domains/URLs (if applicable)
- Domain age and registration info
- SSL certificate analysis
- Known malicious associations
- Hosting infrastructure

#### File Hashes (if applicable)
- Detection rates
- Malware family classification
- Behavioral indicators
- First/last seen dates

### ⚡ Threat Assessment

| Indicator | Risk Level | Confidence | Primary Concern |
|-----------|------------|------------|-----------------|
| ... | ... | ... | ... |

### 🛡️ Recommended Actions

#### Immediate Actions (0-24 hours)
Actions that should be taken right away if indicators are found in your environment.

#### Short-term Actions (1-7 days)
Preventive measures and additional investigation steps.

#### Long-term Recommendations
Strategic improvements to prevent similar threats.

### 🔗 Related Indicators
Any related indicators or patterns discovered during analysis.

### 📚 References
Links to relevant threat intelligence reports or documentation (if available from the data).

---
*Analysis generated by AI based on multi-source threat intelligence data.*`;

export function buildAnalysisPrompt(iocList: Array<{ type: string; value: string }>, analysisData: Record<string, any>): { system: string; user: string } {
  const iocListFormatted = iocList
    .map((ioc) => `- **${ioc.type.toUpperCase()}**: \`${ioc.value}\``)
    .join('\n');

  const userPrompt = ANALYSIS_USER_PROMPT
    .replace('{{IOC_LIST}}', iocListFormatted)
    .replace('{{ANALYSIS_DATA}}', JSON.stringify(analysisData, null, 2));

  return {
    system: ANALYSIS_SYSTEM_PROMPT,
    user: userPrompt,
  };
}

