/**
 * Detailed Analysis Prompt
 * Comprehensive deep-dive analysis with full technical details
 */

export const DETAILED_SYSTEM_PROMPT = `You are a Principal Security Researcher and Threat Intelligence Expert. You specialize in deep-dive IOC analysis, threat hunting, and incident investigation.

## Your Expertise
- Advanced malware analysis and reverse engineering
- Threat actor profiling and attribution
- Network forensics and traffic analysis
- MITRE ATT&CK framework mapping
- Digital forensics and incident response
- Advanced persistent threat (APT) investigation

## Your Approach
- Exhaustive analysis of all available data
- Cross-reference findings across multiple sources
- Identify subtle patterns and anomalies
- Provide technical depth with strategic context
- Document evidence chain for potential incidents

## Output Requirements
- Comprehensive Markdown formatting
- Include all technical details
- Provide evidence for all conclusions
- Map to threat frameworks where applicable
- Detailed remediation guidance
- Consider false positive possibilities`;

export const DETAILED_USER_PROMPT = `Conduct an exhaustive deep-dive analysis of the following IOC data. Leave no stone unturned.

## Analyzed IOCs
{{IOC_LIST}}

## Complete Analysis Results
\`\`\`json
{{ANALYSIS_DATA}}
\`\`\`

## Required Detailed Analysis Structure

### 📊 Executive Overview
High-level summary for leadership with key risk metrics.

---

### 🎯 Indicator Deep-Dive

Analyze each indicator individually with maximum detail:

{{IOC_SECTIONS}}

---

### 🔍 Cross-Correlation Analysis

#### Pattern Recognition
- Identify relationships between indicators
- Common infrastructure or actors
- Timeline correlations
- Behavioral patterns

#### Threat Actor Assessment
- Possible attribution (if evidence exists)
- Known campaigns or operations
- Typical TTPs associated with findings

---

### 🗺️ MITRE ATT&CK Mapping

| Tactic | Technique | Evidence from Analysis |
|--------|-----------|----------------------|
| ... | ... | ... |

---

### ⚠️ Risk Matrix

| Indicator | Severity | Likelihood | Impact | Risk Score |
|-----------|----------|------------|--------|------------|
| ... | ... | ... | ... | ... |

---

### 🛠️ Technical Details

#### Network Indicators
- IP ranges and CIDR blocks involved
- ASN and hosting provider analysis
- Geographic distribution
- Network infrastructure assessment

#### File/Hash Analysis (if applicable)
- Malware classification
- Behavioral indicators
- Code signatures
- Packer/obfuscation detection

#### URL/Domain Analysis (if applicable)
- URL structure analysis
- Domain registration timeline
- SSL/TLS certificate analysis
- Redirect chain analysis

---

### 🚨 Incident Response Guidance

#### Detection Rules
Suggest detection rules or signatures based on findings:
\`\`\`
# YARA/Sigma/Snort rule suggestions
\`\`\`

#### Containment Steps
1. Immediate containment actions
2. Isolation procedures
3. Evidence preservation

#### Eradication Steps
1. Removal procedures
2. Verification steps
3. Root cause elimination

#### Recovery Steps
1. System restoration
2. Service validation
3. Monitoring enhancement

---

### 📋 Action Items by Priority

#### 🔴 Critical (Immediate - Within 1 hour)
- Actions requiring immediate attention

#### 🟠 High (Urgent - Within 24 hours)
- High-priority remediation steps

#### 🟡 Medium (Short-term - Within 1 week)
- Important but not urgent actions

#### 🟢 Low (Long-term - Within 1 month)
- Improvements and hardening measures

---

### 📝 Investigation Notes

- False positive considerations
- Data gaps or limitations
- Recommended additional investigation
- Evidence quality assessment

---

### 📚 References & Resources

- Relevant threat intelligence reports
- Related CVEs or advisories
- Useful tools for further analysis
- External documentation links

---

*Detailed analysis generated by AI. This analysis should be reviewed by security professionals before taking action. Consider organizational context and additional internal data not available in this analysis.*`;

export function buildDetailedPrompt(iocList: Array<{ type: string; value: string }>, analysisData: Record<string, any>): { system: string; user: string } {
  const iocListFormatted = iocList
    .map((ioc) => `- **${ioc.type.toUpperCase()}**: \`${ioc.value}\``)
    .join('\n');

  // Generate individual IOC section headers
  const iocSections = iocList
    .map((ioc, index) => `#### ${index + 1}. ${ioc.type.toUpperCase()}: \`${ioc.value}\`\nAnalyze all available data for this indicator.`)
    .join('\n\n');

  const userPrompt = DETAILED_USER_PROMPT
    .replace('{{IOC_LIST}}', iocListFormatted)
    .replace('{{IOC_SECTIONS}}', iocSections)
    .replace('{{ANALYSIS_DATA}}', JSON.stringify(analysisData, null, 2));

  return {
    system: DETAILED_SYSTEM_PROMPT,
    user: userPrompt,
  };
}

